Repository reliablyhq/documentation, pull requests merged in 2021-07, with the labels that each got.

#309 fixed some outdated docs
  docs/guides/slo/sending-custom-indicators/index.md
Labels: documentation

#314 Adding scanning guide
  docs/getting-started/scanning-k8s/index.md
Labels: documentation, enhancement

#316 Add further clarification around node versioning
  .nvmrc
  README.md
  package-lock.json
  package.json
Labels: documentation

#327 Add entities
  docs/reference/entities/index.md
  docs/reference/entities/indicator.md
  docs/reference/entities/objective.md
  docs/reference/entities/objectiveresult.md
Labels: documentation, enhancement

#328 Fix typos
  docs/reference/entities/index.md
  docs/reference/entities/objective.md
  docs/reference/entities/objectiveresult.md
Labels: bug, documentation

#297 added docs for slack criteria creation
  docs/guides/how-it-works/slack-alerts/index.md
  docs/reference/entities/slackalertcriteria.md
Labels: documentation, enhancement

#329 Add Getting Started for Reliably and Chaos Toolkit
  docs/getting-started/chaos-engineering/index.md
  src/assets/scss/components/_code.scss
  src/components/SetupWithCTK.vue
  src/data/menu-getting-started.yaml
Labels: documentation

#331 Fix typos and add a copy button to scanning-k8s
  docs/getting-started/scanning-k8s/index.md
Labels: documentation
